[versions]
kotest = "6.1.0-RC3"
kotest-plugin = "6.1.0-RC3"
kotlin = "2.2.21"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotest = { id = "io.kotest", version.ref = "kotest-plugin" }
