[versions]
agp = "8.12.0"
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"

mockk = "1.14.9"
kotest = "6.1.3"
kotest-plugin = "6.1.3"

spring-boot = "4.0.1"

ksp = "2.3.6"
gradle-retry = "1.6.4"

allure = "3.0.1"
allure-report = "2.29.1"

# https://developer.android.com/jetpack/androidx/versions/all-channel
androidx-test-runner = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidx-compose-bom = "androidx.compose:compose-bom:2026.01.00"

androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "androidx.compose.material3", name = "material3" }

kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
springmockk = { module = "com.ninja-squad:springmockk", version = "5.0.1" }

kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-extensions-allure = { module = "io.kotest:kotest-extensions-allure", version.ref = "kotest" }

# used for instrumented (device) tests
kotest-runner-junit4 = { module = "io.kotest:kotest-runner-junit4", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

# Versions managed by Spring dependency management and thus excluded here
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
reactor-test = { module = "io.projectreactor:reactor-test" }

spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-webtestclient = { module = "org.springframework.boot:spring-boot-webtestclient" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotest = { id = "io.kotest", version.ref = "kotest-plugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
retry = { id = "org.gradle.test-retry", version.ref = "gradle-retry" }
allure = { id = "io.qameta.allure", version.ref = "allure" }
