[versions]
kotlin = "2.3.0"
kotest = "6.1.0"
postgresql-test-containers = "1.21.4"

[libraries]
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
springmockk = { module = "com.ninja-squad:springmockk", version = "5.0.1" }

# Versions managed by Spring dependency management and thus excluded here

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
postgresql = { module = "org.postgresql:postgresql" }
postgresql-testcontainers = { module = "org.testcontainers:postgresql", version.ref = "postgresql-test-containers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

[bundles]
spring-boot-test = ["spring-boot-starter-test", "spring-boot-starter-data-jpa-test", "spring-boot-testcontainers", "springmockk"]
spring-boot = ["spring-boot-starter", "spring-boot-starter-data-jpa", "spring-boot-starter-flyway"]
kotest = ["kotest-runner-junit5", "kotest-extensions-spring"]
