[versions]
kotest = "6.1.0"
kotest-plugin = "6.1.0"
kotlin = "2.2.21"
ksp = "2.3.4"

[libraries]
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest = { id = "io.kotest", version.ref = "kotest-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
